[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
monitor_speed = 115200

; Required libraries
lib_deps = 
    knolleary/PubSubClient@2.8.0
    adafruit/DHT sensor library@1.4.4
    adafruit/Adafruit Unified Sensor@1.1.14
    bblanchon/ArduinoJson@7.0.4

; Build flags
build_flags = 
    -DCORE_DEBUG_LEVEL=3

; Serial monitor
upload_port = COM5
monitor_port = COM5
